# Generated by Django 2.1.15 on 2020-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='App name'),
        ),
        migrations.AddField(
            model_name='execution',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='App name'),
        ),
    ]
