# Generated by Django 2.1.15 on 2020-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
